import * as React from "react";

export default [{
  "titleNode": "Get Started"
}, {
  "titleNode": "Styles",
  "children": [{
    "titleNode": "Color"
  }, {
    "titleNode": "Icons"
  }, {
    "titleNode": "Layout",
    "children": [{
      "titleNode": "Intro to app UI design"
    }, {
      "titleNode": "Navigation basics",
      "children": [{
        "titleNode": "History and backwards navigation"
      }, {
        "titleNode": "Navigate between two pages"
      }, {
        "titleNode": "Show multiple views"
      }]
    }, {
      "titleNode": "Command basics",
      "children": [{
        "titleNode": "Active canvas"
      }]
    }, {
      "titleNode": "Content basics"
    }, {
      "titleNode": "Screen sizes and breakpoints"
    }, {
      "titleNode": "Define page layouts with XAML"
    }, {
      "titleNode": "Layout panels",
      "children": [{
        "titleNode": "Custom panels"
      }, {
        "titleNode": "Custom panel example: BoxPanel"
      }]
    }, {
      "titleNode": "Alignment, margins, and padding"
    }, {
      "titleNode": "Creating app layouts with Grid and StackPanel"
    }]
  }, {
    "titleNode": "Motion"
  }, {
    "titleNode": "Sound"
  }, {
    "titleNode": "Typography",
    "children": [{
      "titleNode": "Fonts"
    }, {
      "titleNode": "Segoe MDL2 icons"
    }]
  }, {
    "titleNode": "Styling controls",
    "children": [{
      "titleNode": "XAML Control templates"
    }, {
      "titleNode": "ResourceDictionary and XAML resource references"
    }, {
      "titleNode": "XAML theme resources"
    }]
  }]
}, {
  "titleNode": "Components",
  "expanded": true,
  "children": [{
    "titleNode": "Intro"
  }, {
    "titleNode": "Index of controls by function"
  }, {
    "titleNode": "CommandBar"
  }, {
    "titleNode": "AutoSuggestBox"
  }, {
    "titleNode": "Button"
  }, {
    "titleNode": "CheckBox"
  }, {
    "titleNode": "ColorPicker"
  }, {
    "titleNode": "Date and time",
    "children": [{
      "titleNode": "Calendar date picker"
    }, {
      "titleNode": "Calendar view"
    }, {
      "titleNode": "Date picker"
    }, {
      "titleNode": "Time picker"
    }]
  }, {
    "titleNode": "Dialogs and flyouts"
  }, {
    "titleNode": "Flip view"
  }, {
    "titleNode": "Hub"
  }, {
    "titleNode": "Hyperlinks"
  }, {
    "titleNode": "Images and image brushes"
  }, {
    "titleNode": "Inking controls"
  }, {
    "titleNode": "Lists",
    "children": [{
      "titleNode": "List view and grid view"
    }, {
      "titleNode": "List view item templates"
    }, {
      "titleNode": "Inverted lists"
    }, {
      "titleNode": "Pull-to-refresh"
    }, {
      "titleNode": "Nested UI"
    }]
  }, {
    "titleNode": "Master/details"
  }, {
    "titleNode": "Media playback",
    "children": [{
      "titleNode": "Custom transport controls"
    }]
  }, {
    "titleNode": "Menus and context menus"
  }, {
    "titleNode": "Nav pane"
  }, {
    "titleNode": "Progress"
  }, {
    "titleNode": "Radio button"
  }, {
    "titleNode": "Scrolling and panning controls"
  }, {
    "titleNode": "Search"
  }, {
    "titleNode": "Semantic zoom"
  }, {
    "titleNode": "Slider"
  }, {
    "titleNode": "Split view"
  }, {
    "titleNode": "Tabs and pivot"
  }, {
    "titleNode": "Text",
    "children": [{
      "titleNode": "Labels"
    }, {
      "titleNode": "Password box"
    }, {
      "titleNode": "Rich edit box"
    }, {
      "titleNode": "Rich text block"
    }, {
      "titleNode": "Text block"
    }, {
      "titleNode": "Text box"
    }]
  }, {
    "titleNode": "Tiles, badges, and notifications",
    "children": [{
      "titleNode": "Tiles"
    }, {
      "titleNode": "Adaptive tiles",
      "children": [{
        "titleNode": "Adaptive tiles schema"
      }]
    }, {
      "titleNode": "Tile and icon asset guidelines"
    }, {
      "titleNode": "Special tile templates"
    }, {
      "titleNode": "Adaptive and interactive toast notifications"
    }, {
      "titleNode": "Badge notifications"
    }, {
      "titleNode": "Notifications visualizer"
    }, {
      "titleNode": "Notification delivery methods"
    }, {
      "titleNode": "Local tile notfications"
    }, {
      "titleNode": "Periodic notifications"
    }, {
      "titleNode": "Windows Push Notification Services (WNS)",
      "children": [{
        "titleNode": "Code generated by the push notification wizard"
      }]
    }, {
      "titleNode": "Raw notifications"
    }]
  }, {
    "titleNode": "Toggle"
  }, {
    "titleNode": "Tooltip"
  }, {
    "titleNode": "Web view"
  }]
}, {
  "titleNode": <a style={{ color: "inherit", textDecoration: "underline" }} href="https://docs.microsoft.com/en-us/windows/uwp/design-downloads/" target="_blank">Microsoft Design Language</a>
}, {
  "titleNode": <a style={{ color: "inherit", textDecoration: "underline" }} href="https://docs.microsoft.com/en-us/windows/uwp/design-downloads/" target="_blank">Downloads</a>
}];
