import * as React from "react";

export default [{
  "titleNode": "Get Started"
}, {
  "titleNode": "Styles",
  "children": [{
    "titleNode": "Color"
  }, {
    "titleNode": "Icons"
  }, {
    "titleNode": "Layout",
    "children": [{
      "titleNode": "Intro to app UI design"
    }, {
      "titleNode": "Navigation basics",
      "children": [{
        "titleNode": "History and backwards navigation"
      }, {
        "titleNode": "Navigate between two pages"
      }, {
        "titleNode": "Show multiple views"
      }]
    }, {
      "titleNode": "Command basics",
      "children": [{
        "titleNode": "Active canvas"
      }]
    }, {
      "titleNode": "Content basics"
    }, {
      "titleNode": "Screen sizes and breakpoints"
    }, {
      "titleNode": "Define page layouts with XAML"
    }, {
      "titleNode": "Layout panels",
      "children": [{
        "titleNode": "Custom panels"
      }, {
        "titleNode": "Custom panel example: BoxPanel"
      }]
    }, {
      "titleNode": "Alignment, margins, and padding"
    }, {
      "titleNode": "Creating app layouts with Grid and StackPanel"
    }]
  }, {
    "titleNode": "Motion"
  }, {
    "titleNode": "Typography",
    "children": [{
      "titleNode": "Fonts"
    }, {
      "titleNode": "Segoe MDL2 icons"
    }]
  }, {
    "titleNode": "Styling Components",
    "children": [{
      "titleNode": "Use InlineStyle replace the default style"
    }, {
      "titleNode": "Custom theme"
    }]
  }]
}, {
  "titleNode": "Components",
  "children": [{
    "titleNode": "Intro"
  }, {
    "titleNode": "Index of components by function"
  }, {
    "titleNode": "CommandBar"
  }, {
    "titleNode": "AutoSuggestBox"
  }, {
    "titleNode": "Button"
  }, {
    "titleNode": "CheckBox"
  }, {
    "titleNode": "ColorPicker"
  }, {
    "titleNode": "Date Pickers",
    "children": [{
      "titleNode": "CalendarDatePicker"
    }, {
      "titleNode": "CalendarView"
    }, {
      "titleNode": "DatePicker"
    }, {
      "titleNode": "TimePicker"
    }]
  }, {
    "titleNode": "Dialogs and flyouts"
  }, {
    "titleNode": "Flip view"
  }, {
    "titleNode": "Hub"
  }, {
    "titleNode": "Hyperlinks"
  }, {
    "titleNode": "Image"
  },  {
    "titleNode": "Lists",
    "children": [{
      "titleNode": "List view and grid view"
    }, {
      "titleNode": "List view item templates"
    }, {
      "titleNode": "Inverted lists"
    }, {
      "titleNode": "Pull-to-refresh"
    }, {
      "titleNode": "Nested UI"
    }]
  }, {
    "titleNode": "Master/details"
  }, {
    "titleNode": "Media playback",
    "children": [{
      "titleNode": "Custom transport controls"
    }]
  }, {
    "titleNode": "Menus and context menus"
  }, {
    "titleNode": "NavPane"
  }, {
    "titleNode": "Progress"
  }, {
    "titleNode": "Radio button"
  }, {
    "titleNode": "Scrolling and panning controls"
  }, {
    "titleNode": "Search"
  }, {
    "titleNode": "SemanticZoom"
  }, {
    "titleNode": "Slider"
  }, {
    "titleNode": "SplitView"
  }, {
    "titleNode": "Tabs and pivot"
  }, {
    "titleNode": "Text",
    "children": [{
      "titleNode": "Labels"
    }, {
      "titleNode": "PasswordBox"
    }, {
      "titleNode": "RichEditBox"
    }, {
      "titleNode": "Rich text block"
    }, {
      "titleNode": "Text block"
    }, {
      "titleNode": "TextBox"
    }]
  }, {
    "titleNode": "Tiles, badges, and notifications",
    "children": [{
      "titleNode": "Tiles"
    }, {
      "titleNode": "Adaptive tiles",
      "children": [{
        "titleNode": "Adaptive tiles schema"
      }]
    }, {
      "titleNode": "Tile and icon asset guidelines"
    }, {
      "titleNode": "Special tile templates"
    }, {
      "titleNode": "Adaptive and interactive toast notifications"
    }, {
      "titleNode": "Badge notifications"
    }, {
      "titleNode": "Notifications visualizer"
    }, {
      "titleNode": "Notification delivery methods"
    }, {
      "titleNode": "Local tile notfications"
    }, {
      "titleNode": "Periodic notifications"
    }, {
      "titleNode": "Windows Push Notification Services (WNS)",
      "children": [{
        "titleNode": "Code generated by the push notification wizard"
      }]
    }, {
      "titleNode": "Raw notifications"
    }]
  }, {
    "titleNode": "Toggle"
  }, {
    "titleNode": "Tooltip"
  }]
}, {
  "titleNode": "Resources"
}, {
  "titleNode": "Examples"
}, {
  "titleNode": <a style={{ color: "inherit", textDecoration: "underline" }} href="http://fluent.microsoft.com/" target="_blank">Fluent Design System</a>
}, {
  "titleNode": <a style={{ color: "inherit", textDecoration: "underline" }} href="https://docs.microsoft.com/en-us/windows/uwp/design-downloads/" target="_blank">Design Toolkits</a>
}];
