import * as React from "react";

export default [{
  "titleNode": "Get Started"
}, {
  "titleNode": "Layout"
}, {
  "titleNode": "Styles",
  "children": [{
    "titleNode": "Colors"
  }, {
    "titleNode": "Icons"
  }, {
    "titleNode": "Animation"
  }, {
    "titleNode": "Acrylic"
  }, {
    "titleNode": "Reveal",
    hidden: true
  }, {
    "titleNode": "Typography"
  }, {
    "titleNode": "Fonts"
  }, {
    "titleNode": "Styling Components"
  }, {
    "titleNode": "Custom Theme"
  }]
}, {
  "titleNode": "Components",
  "children": [{
    "titleNode": "Animate"
  }, {
    "titleNode": "AppBarButton"
  }, {
    "titleNode": "AutoSuggestBox"
  }, {
    "titleNode": "Button"
  }, {
    "titleNode": "CheckBox"
  }, {
    "titleNode": "ColorPicker"
  }, {
    "titleNode": "CommandBar"
  }, {
    "titleNode": "ContentDialog"
  }, {
    "titleNode": "DatePickers",
    "children": [{
      "titleNode": "CalendarDatePicker"
    }, {
      "titleNode": "CalendarView"
    }, {
      "titleNode": "DatePicker"
    }, {
      "titleNode": "TimePicker"
    }]
  }, {
    "titleNode": "Dialog"
  }, {
    "titleNode": "DropDownMenu"
  }, {
    "titleNode": "FlipView"
  }, {
    "titleNode": "Flyout"
  }, {
    "titleNode": "FloatNav"
  }, {
    "titleNode": "HyperLink"
  }, {
    "titleNode": "Icon"
  }, {
    "titleNode": "IconButton"
  }, {
    "titleNode": "Image"
  }, {
    "titleNode": "ListView"
  }, {
    "titleNode": "MarkdownRender"
  }, {
    "titleNode": "MediaPlayer"
  }, {
    "titleNode": "Menu"
  }, {
    "titleNode": "NavigationView"
  }, {
    "titleNode": "PasswordBox"
  }, {
    "titleNode": "ProgressBar"
  }, {
    "titleNode": "ProgressRing"
  }, {
    "titleNode": "RadioButton"
  }, {
    "titleNode": "RatingControl"
  }, {
    "titleNode": "ScrollReveal"
  }, {
    "titleNode": "Separator"
  }, {
    "titleNode": "Slider"
  }, {
    "titleNode": "SplitView"
  }, {
    "titleNode": "SplitViewCommand"
  }, {
    "titleNode": "Tabs"
  }, {
    "titleNode": "TextBox"
  }, {
    "titleNode": "Toggle"
  }, {
    "titleNode": "Tooltip"
  }, {
    "titleNode": "TransformCard"
  }, {
    "titleNode": "TreeView"
  }, {
    "titleNode": "Theme"
  }, {
    "titleNode": "Toast"
  }]
}, {
  "titleNode": "Resources"
}, {
  "titleNode": "Showcase"
}, {
  "titleNode": "Server Side Rendering"
},  {
  "titleNode": "ChangeLog"
}, {
  "titleNode": "Fluent Design System",
  hidden: true,
  "expanded": true,
  "children": [{
    "titleNode": "Z Space"
  }, {
    "titleNode": "WebGL"
  }, {
    "titleNode": "Material"
  }, {
    "titleNode": "Acrylic"
  }, {
    "titleNode": "Reveal"
  }, {
    "titleNode": "ScrollBar",
    hidden: true
  }, {
    "titleNode": "SemanticZoom",
    hidden: true
  }, {
    "titleNode": "Toast",
    hidden: true
  }, {
    "titleNode": "GridView",
    hidden: true
  }, {
    "titleNode": "PullRefresh",
    hidden: true
  }]
}];
